"""add transaction analytics indexes

Revision ID: f275f1174094
Revises: c76cc951555f
Create Date: 2026-09-02 18:49:08.097966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f275f1174094'
down_revision: Union[str, Sequence[str], None] = 'c76cc951555f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('transactions', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index('ix_transactions_payment_method_created_at', 'transactions', ['payment_method', 'created_at'], unique=False)
    op.create_index('ix_transactions_payment_method_status_created_at', 'transactions', ['payment_method', 'status', 'created_at'], unique=False)
    op.create_index('ix_transactions_status_created_at', 'transactions', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_status_created_at', table_name='transactions')
    op.drop_index('ix_transactions_payment_method_status_created_at', table_name='transactions')
    op.drop_index('ix_transactions_payment_method_created_at', table_name='transactions')
    op.alter_column('transactions', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transactions', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
