"""add users authentication

Revision ID: 27c966a500c2
Revises: f275f1174094
Create Date: 2026-09-02 22:24:55.180757

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27c966a500c2'
down_revision: Union[str, Sequence[str], None] = 'f275f1174094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('hashed_password', sa.String(length=255), nullable=False),
                    sa.Column('is_active', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('transactions', 'amount',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    type_=sa.Numeric(precision=18, scale=2),
                    existing_nullable=False)
    op.alter_column('transactions', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    op.alter_column('transactions', 'amount',
                    existing_type=sa.Numeric(precision=18, scale=2),
                    type_=sa.DOUBLE_PRECISION(precision=53),
                    existing_nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
